name: mapbox_gl_modified_web
description: Web platform implementation of mapbox_gl
version: 0.16.0
homepage: https://github.com/ithebest/mapbox_gl_modified

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_modified_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.9.1
  mapbox_gl_modified_platform_interface:
    git:
      url: https://github.com/asbn223/mapbox_gl_modified_platform_interface

  mapbox_gl_dart: ^0.2.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
